docker/flowg.dockerfile
internal/version.go

The built binary requires the shared libraries `libgcc` and `libc`.
While `libc` is already present in the `alpine` Docker image, `libgcc` is not.

:whale: :bug: Add missing `libgcc` package in runner

---

README.md
cmd/flowg/serve.go
internal/app/bootstrap/auth.go
internal/app/bootstrap/pipelines.go
internal/app/version.go

In order to facilitate the deployment, we need to:
- create an `admin` role with every permission **if and only if** no role exists
- create a `root` user (with `root` password) with the role `admin` **if and only if** no user exist
- create a `default` pipeline that simply route all logs to a `default` stream **if and only if** no pipeline exist
This bootstrap is done at startup.

:wrench: :sparkles: Bootstrap initial configuration

---

web/components/code-editor/package-lock.json
web/components/code-editor/package.json
web/components/code-editor/src/CodeEditor.tsx
web/components/code-editor/src/vrl-highlighter.ts

Syntax highlighting and autocompletion are always nice when editing code. The VRL Web Playground uses Monaco-Editor and provides a custom highlighter for it, so we will use it instead of CodeMirror.
**NB:** Monaco Editor is the technology behind VS Code.

:lipstick: Add VRL syntax highlighting and autocompletion

---

api/main.go
api/watch_logs.go
cmd/flowg/serve.go
internal/app/logging/middleware.go
internal/data/lognotify/main.go
internal/data/lognotify/types.go
internal/data/lognotify/worker.go
internal/data/pipelines/main.go
internal/data/pipelines/types.go

In order to improve inter-operability, we add a new `watch_logs` API operation which implements **Sever-Sent Events**, as a streaming response with `text/event-stream` content type.
Users are able to watch logs of a specific stream in real time:
```
$ curl -H "Authorization: Bearer <token>" http://localhost:5080/api/v1/streams/{stream}/logs/watch
id: <log key>
event: log
data: {"timestamp": "...", "fields": {...}}
...
```

:sparkles: Add `watch_logs` API operation

---

internal/app/version.go
internal/data/pipelines/flow.go
internal/data/pipelines/types.go
web/components/floweditor/src/flow/FlowEditor.tsx
web/components/floweditor/src/flow/NodeSelector.tsx
web/components/floweditor/src/flow/nodes/PipelineNode.tsx

For reusability, it can be useful to split a flow into multiple smaller flows. This PR adds a new *Pipeline Node* which will run the log entry through another pipeline.

:sparkles: Add Pipeline nodes

---

Taskfile.yml
docker/flowg.dockerfile
internal/ffi/vrl/ffi_test.go
internal/ffi/vrl/rust-crate/src/runner.rs

In *FlowG*, a log record is a flat map of `string -> string`. But a VRL script can return more complex/nested values.
In order to properly serialize the result of a VRL script to the format FlowG expects:
- `Bytes`, `Regex`, `Timestamp`, `Integer`, `Float` and `Boolean` are translated to UTF-8 strings
- `Null` is translated to an empty string
- `Object` and `Array` are flattened
For example, the following script:
```vrl
.foo = 42
.bar.baz = [1, 2, 3, "a"]
.
```
Would return the following object (given an empty record as input):
```json
{
"foo": 42,
"bar": {
"baz": [1, 2, 3, "a"]
}
}
```
Once flattened and with every value serialized to a string:
```json
{
"foo": "42",
"bar.baz.0": "1",
"bar.baz.1": "2",
"bar.baz.2": "3",
"bar.baz.3": "a"
}
```

:sparkles: Flatten results of VRL scripts

---

cmd/flowg/admin_role_create.go
cmd/flowg/admin_role_delete.go
cmd/flowg/admin_role_list.go
cmd/flowg/admin_token_create.go
cmd/flowg/admin_user_create.go
cmd/flowg/admin_user_delete.go
cmd/flowg/admin_user_list.go
cmd/flowg/serve.go
internal/data/auth/database.go
internal/data/config/backend.go
internal/data/config/main.go
internal/data/config/system_alerts.go
internal/data/config/system_pipelines.go
internal/data/config/system_transformers.go
internal/data/logstorage/main.go

See: #77
In order to facilitate the implementation of unit tests, we need the ability to open databases in "In Memory" mode.

:sparkles: Add In-Memory mode (for testing purpose)

---

api/login.go
api/logout.go
api/main.go
api/whoami.go
internal/data/auth/middleware_api.go
tests/e2e/integration/acl_tokens.hurl
tests/e2e/integration/auth.hurl

In order to be able to build a client-side web application for FlowG, we need the API to support cookie-based authentication, thus avoiding the need to store a token on the client.

:passport_control: Add Cookie-based authentication to API

---

api/watch_logs.go
internal/data/lognotify/main.go
internal/data/lognotify/notify_test.go
internal/data/lognotify/types.go
internal/data/lognotify/worker.go
internal/data/pipelines/nodes.go

An `actor.Mailbox` uses internally a growing queue, which avoids blocking the goroutine when sending messages.
Let's use this instead of normal Go channels for the `lognotify.Lognotifier`

:recycle: Avoid blocking notifications

---

api/watch_logs.go
internal/data/lognotify/main.go
internal/data/lognotify/notify_test.go
internal/data/lognotify/types.go
internal/data/lognotify/worker.go
internal/data/pipelines/nodes.go

The `LogNotifier.Subscribe()` function does not block until channel is ready to consume messages. In the test suite, this leads to a race condition where the message sent in `LogNotifier.Notify()` is received first, thus lost as there is no subscriber yet. Which means the test will fail by timeout while waiting for the message.

:recycle: :white_check_mark: Fix Race condition in test suite

---

web/app/src/components/editors/alert/dialog.tsx
web/app/src/components/editors/alert/index.tsx
web/app/src/components/editors/pipeline/nodes/alert.tsx
web/app/src/components/editors/pipeline/nodes/router.tsx
web/app/src/components/editors/stream/dialog.tsx
web/app/src/components/editors/stream/index.tsx
web/app/src/lib/api/operations/config.ts
web/app/src/views/app/alerts/item.tsx
web/app/src/views/app/storage/item.tsx

:sparkles: Add missing edit buttons for alerts and streams

---

internal/utils/ffi/vrl/ffi.go

When building in WSL, I get `undefined reference to` errors related to functions provided by `math.h` when Go is trying to link with the internal `vrl` static library.

:bug: Link `vrl` cgo library with `math.h`

---

docker/flowg.dockerfile

Alpine 3.21 has been out for a month now, this PR upgrades all stages of the Docker image to this new version.
https://alpinelinux.org/posts/Alpine-3.21.0-released.html

:arrow_up: :whale: upgrade to alpine 3.21

---

.gitignore
cmd/flowg/admin_backup.go
cmd/flowg/admin_restore.go
internal/storage/config/main.go
internal/utils/filestore/backend.go
internal/utils/filestore/main.go
internal/utils/filestore/messages.go
website/docs/guides/backup.md

Instead of copying the configuration folder into the backup directory, and then copying back the files one by one in the configuration storage during the restore; let's add `Backup()` and `Restore()` methods to the configuration storage so that:
- its interface is the same as the auth storage and log storage interfaces
- the CLI commands source code is easier to read
- in the future, plugging in other `io.Writer` / `io.Reader` would allow backuping/restoring using other methods than the filesystem (like over a socket, or via the HTTP API)

:recycle: Better offline backup for configuration storage

---

web/app/package-lock.json

When installing NodeJS dependencies, there was a warning about an indirect dependency still not supporting React 19. A fix has been published a few days ago to upgrade that dependency.
So let's just run:
```
npm outdated
npm update
```
In order to upgrade all dependencies.

:pushpin: Update all dependencies in `/web/app`

---

website/docs/api.mdx
website/docusaurus.config.ts
website/package-lock.json
website/package.json
website/redocly.yaml
website/src/openapi.json

Using the [Redocusaurus](http://redocusaurus.vercel.app/) plugin, we can integrate the API documentation generated from the OpenAPI schema, so that we don't need to run FlowG in order to access the documentation.

:memo: Integrate OpenAPI documentation to website

---

.github/workflows/release-package.yml
docker/flowg.dockerfile

At the moment, the binary that Go produces is quite big (around 50MB). It can be reduced using the `-ldflags="-s -w"` at compile-time, to strip the binary and gain a few MBs.
The tool [UPX](https://upx.github.io) can be used to compress the executable further and decompress it at runtime.
With both of those options, the `flowg-server` binary is now around 20MB, 60% less!
This lead to a smaller Docker image, and a smaller release archive.

:package: Reduce executable size

---

.github/workflows/ci-package.yml
.github/workflows/release-package.yml
docker/flowg.dockerfile

The Dockerfile was explicitly downloading the `amd64-linux` version of UPX (introduced in #527), which obviously does not work for the `arm64-linux` version of the Docker image that is built for each release.

:green_heart: :package: Fix release build

---

cmd/flowg-health/env.go
cmd/flowg-health/main.go
docker/flowg.dockerfile
go.mod

See #545
Since the healthcheck endpoint can be customized via the CLI options or environment variables, we needed a `flowg-health` binary, which given a PID would parse the process's command line (via `/proc/${pid}/cmdline`) to extract the information (if present), and then would perform the HTTP request.

:whale: Add Healthcheck to Docker image

---

internal/app/bootstrap/pipelines.go
web/app/package-lock.json
web/app/package.json
web/app/src/components/editors/pipeline/flow-editor.tsx

When we add a node to the pipeline, we need to generate an ID that should be unique.
Until now, the generated ID was of the form `node-${nodes.length}`. This is fine if you never remove nodes. But once you start removing nodes, you end up with conflicting IDs. This results in a glitch in the editor where nodes with conflicting IDs can disappear:
To fix that, we use an UUIDv4 to ensure that nodes always have a unique ID (honestly, this should have been done from the start, I don't know what I was thinking).
> **NB:** This is a non-breaking change, existing pipelines who used the old IDs will still work.

:bug: Ensure Node IDs are always unique

---

internal/utils/api/middleware.go
internal/utils/auth/jwt.go
tests/specs/api/acl_roles.hurl
tests/specs/api/acl_tokens.hurl
tests/specs/api/acl_users.hurl
tests/specs/api/auth.hurl
tests/specs/api/backup.hurl
tests/specs/api/forwarders.hurl
tests/specs/api/permissions.hurl
tests/specs/api/pipelines.hurl
tests/specs/api/retention.hurl
tests/specs/api/streams.hurl
tests/specs/api/transformers.hurl
tests/specs/web/account.robot
tests/specs/web/resources/logging.resource
tests/src/benchmark/conftest.py
tests/src/benchmark/utils.py
tests/src/conftest.py
web/app/src/lib/api/request.ts
website/docs/guides/backup.md
website/docs/usecases/uptime-kuma.mdx

Personal Access Tokens were generated with the `pat_` prefix.
JSON Web Tokens had no prefix.
In both cases, to authenticate against the API, the `Authorization` header required the prefix `Bearer pat:` or `Bearer jwt:`.
Therefore, for a Personal Access Token, you had to write:
```
Authorization: Bearer pat:pat_...
```
Which is redundant.
Instead, let's remove the `pat:` and `jwt:` prefixes from the HTTP header, and add the `jwt_` prefix to JSON Web Tokens.

:boom: :recycle: Uniformize token formats

---

api/ingest_logs_otlp.go
internal/app/logging/main.go
internal/app/logging/middleware.go
internal/models/logrecord.go

Traefik sends OTLP requests with the `Content-Encoding` set to `gzip`, which we did not handle.
On top of that, the `AnyValue` model was not parsed correctly, and we were getting columns like `string_value:"hello"` instead of `hello`.

:bug: Handle GZIP encoded OTLP requests

---

tests/pdm.lock
tests/pyproject.toml
tests/specs/api/acl_roles.hurl
tests/specs/api/acl_tokens.hurl
tests/specs/api/acl_users.hurl
tests/specs/api/pipelines.hurl
tests/specs/api/retention.hurl
tests/src/conftest.py

In the test suite, if for some reason the container's healthcheck failed, the container was not stopped, and no logs were collected. This led to the volume not being deleted either.
The PR #547 also introduced a `HEALTHCHECK` directive in the Dockerfile, which makes our custom healthcheck obsolete.

:white_check_mark: :bug: Teardown container if healthcheck fails

---

tests/config/mockserver-config.json
tests/specs/api/forwarder_http.hurl
tests/specs/api/forwarders.hurl
tests/src/_lib/mockserver_utils.py
tests/src/api/test_e2e.py
tests/src/conftest.py

The forwarders are making requests to third-party services. In order to test them, we need to mock the third-party services.
In the current test suite, we relied on https://httpbin.org for the HTTP Forwarder, which is fine, but not enough for other forwarders (Datadog, and upcoming Splunk HEC in #685).
Instead, with https://mock-server.com, we can define "expectations" to match HTTP requests and return responses accordingly.

:white_check_mark: Add Mockserver

---

internal/models/forwarder_v2.go
internal/models/forwarder_v2_splunk.go
internal/models/forwarder_v2_splunk_test.go
tests/config/mockserver-config.json
tests/specs/api/forwarder_splunk.hurl

Decision Record:
Add Splunk HEC Forwarder
Summary
Add support for Splunk HTTP Event Collector (HEC) as a new forwarder type.
Changes
- Added `splunk` forwarder with endpoint and token config
- Implemented HTTP POST to Splunk HEC with proper payload and headers
- Added unit and integration tests (HURL)

✨ add Splunk forwarder support

---

internal/models/forwarder_v2.go
internal/models/forwarder_v2_otlp.go
internal/models/forwarder_v2_otlp_test.go
tests/config/mockserver-config.json
tests/specs/api/forwarder_otlp.hurl
web/app/src/components/editors/forwarder/index.tsx
web/app/src/components/editors/forwarder/otlp.tsx
web/app/src/lib/models/forwarder/index.ts
web/app/src/lib/models/forwarder/otlp.ts
web/app/src/views/app/forwarders/new-btn/modal.tsx
website/docs/usecases/otlp.mdx

Added support for OpenTelemetry Protocol (OTLP) as a new forwarder type for exporting logs to OTLP-compatible endpoints.
- Added OTLP forwarder with configurable endpoint and headers
- Added unit and integration tests for OTLP functionality

✨ add OpenTelemetry forwarder support

---

api/change_password.go
api/ingest_logs_otlp.go
api/ingest_logs_struct.go
api/ingest_logs_text.go
cmd/flowg-server/cmd/cli.go
cmd/flowg-server/cmd/env.go
cmd/flowg-server/cmd/main.go
internal/app/logging/context.go
internal/app/logging/main.go
internal/app/logging/middleware.go

At the moment, the only way we have to configure the logging level is through the `--verbose` option, which enables debug logging and erroneous response body logging.
On top of that, we are logging in the access log every request to API. But some routes should not log:
- "change password": for security reasons, we should not log requests to this route
- log ingestion: let's say we are forwarding FlowG's logs into itself, those routes would create a loop
This PR introduce a new CLI options `--loglevel` and its environment variable counterpart `FLOWG_LOGLEVEL` which can be set to either `debug`, `info`, `warn` or `error` (case insensitive).
> **NB:** enabling verbose logging through `--verbose` or `FLOWG_VERBOSE` ignores the `--loglevel` option.
It also switched the mentioned routes to …

:recycle: Better logging

---

api/main.go
internal/app/bootstrap/auth.go
internal/app/bootstrap/pipelines.go
internal/app/server/bootstrap.go
internal/cluster/delegate.go
internal/cluster/main.go
internal/cluster/node_state.go
internal/cluster/transport.go
internal/engines/lognotify/main.go
internal/engines/pipelines/context.go
internal/engines/pipelines/main.go
internal/engines/pipelines/process.go
internal/engines/pipelines/types.go
internal/services/http/main.go
internal/services/mgmt/main.go
internal/services/mgmt/server.go
internal/services/syslog/main.go
internal/storage/auth/main.go
internal/storage/auth/migrator.go
internal/storage/config/main.go
internal/storage/config/migrator.go
internal/storage/log/gc.go
internal/storage/log/main.go
internal/utils/api/decorator.go
internal/utils/api/middleware.go
internal/utils/kvstore/main.go

See: #77
When working with unit tests, we may want to mock the dependencies of the code being tested. To facilitate this, let's expose said dependencies as interfaces instead of concrete types.

:recycle: Use Interfaces instead of concrete types

---

go.mod
internal/engines/lognotify/mock.go
internal/engines/pipelines/mock.go
internal/storage/auth/mock.go
internal/storage/config/mock.go
internal/storage/log/mock.go
internal/utils/kvstore/mock.go

In PR #858, we introduced interfaces to facilitate testing. Now, we add configurable mocks to further facilitate testing.

:clown_face: Add mocks

---

api/main.go
api/middlewares/elastic.go
api/middlewares/elastic_test.go
api/middlewares/main.go
tests/specs/api/ingest_logs_struct.hurl
tests/specs/api/middleware_elastic.hurl
website/docs/usecases/interoperability/elasticsearch.md
website/docs/usecases/interoperability/index.md

- See #853
- Close #854
- Close #855

:sparkles: Minimal ElasticSearch Input Middleware

---

internal/models/forwarder_v2_otlp.go
internal/models/forwarder_v2_otlp_test.go
tests/specs/api/forwarder_otlp.hurl

The OpenTelemetry forwarder's datamodel had a nested `Config` field which was ignored by the editor in the Web UI.
It also embedded an `*http.Client` in the structure, in an attempt to cache it, but the forwarder structure is instantiated for every log (we should look into this later on by the way), so it is not a useful optimization at this point.

:bug: OTLP forwarder should not nest the configuration
